name: Build Docker Containers (ARM64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: depot-ubuntu-22.04-4

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Depot CLI
      uses: depot/setup-action@v1
      env:
        DEPOT_TOKEN: ${{ secrets.DEPOT_API_TOKEN }}

    - name: Build and Push Docker image with Depot
      run: |
        depot build . \
          --project 2g4vskn96j \
          --file Dockerfile \
          --tag ${{ env.REGISTRY }}/${{ github.repository }}:latest \
          --platform linux/arm64 \
          --build-arg ARCH=arm64 \
          --cache-from type=gha,scope=build-arm64 \
          --cache-to type=gha,mode=max,scope=build-arm64 \
          --push
      env:
        DEPOT_TOKEN: ${{ secrets.DEPOT_API_TOKEN }}